name: Build and Push VS Code CLI Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 允许写入内容

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check VS Code CLI newest version
        id: check-version
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/microsoft/vscode/releases/latest)
          NEW_VERSION=$(echo $LATEST_RELEASE | jq -r '.tag_name')
          echo "New VS Code CLI version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Read last built version
        id: read-last-version
        run: |
          if [ -f version.txt ]; then
            LAST_BUILT_VERSION=$(cat version.txt)
          else
            LAST_BUILT_VERSION="none"
          fi
          echo "LAST_BUILT_VERSION=$LAST_BUILT_VERSION" >> $GITHUB_ENV

      - name: Determine if build is necessary
        id: determine-build
        run: |
          if [ "${{ env.NEW_VERSION }}" = "${{ env.LAST_BUILT_VERSION }}" ]; then
            echo "Skipping build; versions match."
            echo "SKIP_BUILD=true" >> $GITHUB_ENV  # 设置跳过构建的标志
          else
            echo "SKIP_BUILD=false" >> $GITHUB_ENV  # 需要构建
          fi

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-version
    strategy:
      matrix:
        platform: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: maojiaxing
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set architecture variable
        id: set-arch
        run: |
          if [ "${{ matrix.platform }}" == "amd64" ]; then
            echo "ARCH=x64" >> $GITHUB_ENV  # 将 amd64 映射到 x64
          else
            echo "ARCH=${{ matrix.platform }}" >> $GITHUB_ENV  # arm64 保持不变
          fi
          
      - name: Build and push Docker image
        id: build-docker-image
        if: ${{ env.SKIP_BUILD == 'false' }}
        run: |
          docker buildx build \
            --platform linux/${{ matrix.platform }} \
            --tag maojiaxing/vscode-cli:${{ matrix.platform }}-${{ env.NEW_VERSION }} \
            --build-arg VSCODE_CLI_PLATFORM=${{ env.ARCH }} \
            --build-arg VSCODE_CLI_VERSION=${{ env.NEW_VERSION }} \
            --file ./Dockerfile \
            --output type=docker .
            
      - name: Create and push Docker manifest
        id: build-and-push-manifest
        if: ${{ env.SKIP_BUILD == 'false' }}
        run: |
          docker manifest create \
            maojiaxing/vscode-cli:${{ env.NEW_VERSION }} \
            maojiaxing/vscode-cli:amd64-${{ env.NEW_VERSION }} \
            maojiaxing/vscode-cli:arm64-${{ env.NEW_VERSION }}
            
          docker manifest create \
            maojiaxing/vscode-cli:latest \
            maojiaxing/vscode-cli:amd64-${{ env.NEW_VERSION }} \
            maojiaxing/vscode-cli:arm64-${{ env.NEW_VERSION }}

          docker manifest push maojiaxing/vscode-cli:latest
          docker manifest push maojiaxing/vscode-cli:${{ env.NEW_VERSION }}
           

  record-build-version:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Update version in repository
        id: record-build-version
        if: ${{ env.SKIP_BUILD == 'false' }}
        run: |
          echo "${{ env.NEW_VERSION }}" > version.txt
          git config --global user.email "maojiaxing.tech@gmail.com"            
          git config --global user.name "GitHub Actions"
          git add version.txt
          git commit -m "Update version to ${{ env.NEW_VERSION }}"
          git push
